@startuml
'https://plantuml.com/class-diagram
package "IdentitityAccess" {
  package "model" {
  }

  package "services" {
  }

  package "pages" {
    class LoginWorkshopPage <<Component>> {
      +ngOnInit(): void
      +onLogin(): void
    }

    class RegisterWorkshopComponent <<Component>> {
      +onRegister(): void
    }
    class EditProfilePage <<Component>> {
      +onUpdateProfile(): void
    }
  }
  package "components" {
    class LoginWorkshopFormComponent <<Component>> {
          +ngOnInit(): void
          +onLogin(): void
        }

        class RegisterWorkshopFormComponent <<Component>> {
          +onRegister(): void
    }
  }
}


@enduml
