@startuml
package "CarTracking" {
  package "models" {
    class Car <<Entity>> {
      -plateNumber: string
      -location: string
      -trackingCode: string
      +track(): void
    }
  }
  package "services" {

  }
  package "pages" {
    class TrackingPageComponent <<Page>> {
      +onSearchTracking(): void
    }
  }
  package "components" {
    class TrackingFormComponent <<Component>> {}
    class DetailsRepairmentComponent <<Component>> {}
  }
}


@enduml
