@startuml
package "shared" {
  package "components" {
    class WorkshopFilterComponent <<Component>> {}
    class RepairStatusBadgeComponent <<Component>> {}
    class LogoutButtonComponent <<Component>> {}
  }
  package "service" {}
}

package "app" {}

package "public" {
  package "services" {}

  package "pages" {
    class PageNotFoundComponent <<Page>> {}
    class HomeComponent <<Page>> {}
  }

  package "component" {
    class ToolbarComponent <<Component>> {}
    class SideNavigationBarComponent <<Component>> {}
    class FooterContentComponent <<Component>> {}
    class LanguageSwitcherComponent <<Component>> {
      +currentLang: string
      +languages: string[]
      +useLanguage(language: string): void
    }
  }
}


@enduml
