@startuml
package "WorkshopManagement" {
  package "model" {
    class WorkshopInfo <<Entity>> {
      -name: string
      -address: string
      -district: string
      -schedule: string
       -phone : string
       - region : string

    }
  }
  package "service" {
    class WorkshopInfoService <<Service>> {
      +getAll(): Observable<WorkshopInfo[]>
      +getById(id: string): Observable<WorkshopInfo>
      +create(workshop: Workshop): Observable<WorkshopInfo>
      +update(workshop: Workshop): Observable<WorkshopInfo>
      +filterByDistrict(district: string): Observable<WorkshopInfo[]>
    }
    class WorkshopInfoAssembler<<Assembler>>{
    }
    interface WorkshopInfoResponse<<Response>>{
    }
  }
  package "pages" {
    class WorkShopCataloguePage <<Page>> {}
    class WorkshopDetailsPage <<Page>> {}
  }
  package "components" {
    class WorkshopCardComponent <<Component>> {}
    class ScheduleEditorComponent <<Component>> {}
    class WorkShopDetailsComponent <<Component>>{}
    class WorkshopListComponent <<Component>>{}

  }
}



@enduml
